name: 'Update file in Google Drive'
description: 'Updates a file, existing in Google Drive, with a local one'
author: 'Ludovico Novelli'
inputs: 
  credentials:
    description: 'Google Service Account credentials'
    required: true
  localFileToUpload:
    description: 'Local file to upload to GDrive'
    required: true
  remoteFileId:
    description: 'Remote file id to update with local file'
    required: true
  remoteFileName:
    description: 'Name to assign to the new remote file, once uploaded'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'  
  color: 'orange'
